export const formItems = [
  {
    label: "基本属性",
    name: "baseForm",
    rules: {
      statIndctNameCh: [
        { required: true, message: "请填写中文名称", trigger: "blur" },
      ],
      statIndctCode: [
        { required: true, message: "请填写编码", trigger: "blur" },
      ],
      statIndctLevel: [
        { required: true, message: "请填写层级", trigger: "blur" },
      ],
      statIndctSortNum: [
        { required: true, message: "请填写顺序号", trigger: "blur" },
      ],
      statIndctAggregateType: [
        { required: true, message: "请选择汇总类型", trigger: "blur" },
      ],
      statIndctType1: [
        { required: true, message: "请选择指标类型(一)", trigger: "blur" },
      ],
      statIndctType2: [
        { required: true, message: "请选择指标类型(二)", trigger: "blur" },
      ],
      statIndctType3: [
        { required: true, message: "请选择指标类型(三)", trigger: "blur" },
      ],
      statIndctVersion: [
        { required: true, message: "请填写版本", trigger: "blur" },
      ],
    },

    data: [
      {
        label: "名称",
        width: "120px",
        prop: "statIndctNameCh",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "英文名",
        width: "120px",
        prop: "statIndctNameEn",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "编码",
        width: "120px",
        prop: "statIndctCode",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "别名",
        width: "120px",
        prop: "statIndctNicknameCh",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "层级",
        width: "120px",
        prop: "statIndctLevel",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "顺序号",
        width: "120px",
        prop: "statIndctSortNum",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "汇总类型",
        width: "120px",
        prop: "statIndctAggregateType",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "量纲",
        width: "120px",
        prop: "statIndctUmDimension",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "计量单位",
        width: "120px",
        prop: "statIndctUm",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "指标类型(一)",
        width: "120px",
        prop: "statIndctType1",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "指标类型(二)",
        width: "120px",
        prop: "statIndctType2",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "指标类型(三)",
        width: "120px",
        prop: "statIndctType3",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "指标出处",
        width: "120px",
        prop: "statIndctSource",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "版本",
        width: "120px",
        prop: "statIndctVersion",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "版本说明",
        width: "120px",
        prop: "statIndctVersionDesc",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "计算方法",
        width: "120px",
        prop: "statIndctAlgorithm",
        type: "textarea",
        disabled: false,
        placeholder: "",
      },
      {
        label: "指标用途",
        width: "120px",
        prop: "statIndctPurpose",
        type: "textarea",
        disabled: false,
        placeholder: "",
      },
      {
        label: "指标解释",
        width: "120px",
        prop: "statIndctDesc",
        type: "textarea",
        disabled: false,
        placeholder: "",
      },
      {
        label: "内涵定义",
        width: "120px",
        prop: "statIndctIntensionDefine",
        type: "textarea",
        disabled: false,
        placeholder: "",
      },
      {
        label: "外延定义",
        width: "120px",
        prop: "statIndctExtensionDefine",
        type: "textarea",
        disabled: false,
        placeholder: "",
      },
      {
        label: "资料来源",
        width: "120px",
        prop: "statIndctDataSource",
        type: "textarea",
        disabled: false,
        placeholder: "",
      },
      {
        label: "填报说明",
        width: "120px",
        prop: "statIndctFillDesc",
        type: "textarea",
        disabled: false,
        placeholder: "",
      },
    ],
  },
  {
    label: "管理属性",
    name: "manageForm",
    rules: {
      statIndctStatus: [
        { required: true, message: "请选择指标状态", trigger: "blur" },
      ],
      statIndctCreatDate: [
        { required: true, message: "请填写创建时间", trigger: "blur" },
      ],
      statIndctCreatOrgVersion: [
        { required: true, message: "请填写创建机构版本", trigger: "blur" },
      ],
      statIndctManageLevel: [
        { required: true, message: "请填写指标管理级别", trigger: "blur" },
      ],
      statIndctManageOrgVersion: [
        { required: true, message: "请填写管理机构版本", trigger: "blur" },
      ],
      statIndctCheckStatus: [
        { required: true, message: "请选择审批状态", trigger: "blur" },
      ],
    },
    fuData: {},
    data: [
      {
        label: "指标状态",
        width: "120px",
        prop: "statIndctStatus",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "指标启用时间",
        width: "120px",
        prop: "statIndctStartDate",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "指标停用时间",
        width: "120px",
        prop: "statIndctStopDate",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "创建时间",
        width: "120px",
        prop: "statIndctCreatDate",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "创建机构版本",
        width: "120px",
        prop: "statIndctCreatOrgVersion",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "创建机构名称",
        width: "120px",
        prop: "statIndctCreatOrgName",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "创建机构联系人",
        width: "120px",
        prop: "statIndctCreatOrgContact",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "创建机构联系电话",
        width: "120px",
        prop: "statIndctCreatOrgPhone",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "创建机构电子邮箱",
        width: "120px",
        prop: "statIndctCreatOrgEmail",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "指标管理级别",
        width: "120px",
        prop: "statIndctManageLevel",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "管理机构版本",
        width: "120px",
        prop: "statIndctManageOrgVersion",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "管理机构名称",
        width: "120px",
        prop: "statIndctManageOrgName",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "管理机构联系人",
        width: "120px",
        prop: "statIndctManageOrgContact",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "管理机构联系电话",
        width: "120px",
        prop: "statIndctManageOrgPhone",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "管理机构电子邮箱",
        width: "120px",
        prop: "statIndctManageOrgEmail",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "管理机构修订记录",
        width: "120px",
        prop: "statIndctManageOrgRevRec",
        type: "textarea",
        disabled: false,
        placeholder: "",
      },
      {
        label: "提交审批时间",
        width: "120px",
        prop: "statIndctSubmitDate",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "审批时间",
        width: "120px",
        prop: "statIndctCheckDate",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "审批状态",
        width: "120px",
        prop: "statIndctCheckStatus",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "审批意见",
        width: "120px",
        prop: "statIndctCheckOpinion",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "审批机构版本",
        width: "120px",
        prop: "statIndctCheckOrgVersion",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "审批机构名称",
        width: "120px",
        prop: "statIndctCheckOrgName",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "审批机构审批人",
        width: "120px",
        prop: "statIndctCheckOrgApprover",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "审批机构修订记录",
        width: "120px",
        prop: "statIndctCheckOrgRevRec",
        type: "textarea",
        disabled: false,
        placeholder: "",
      },
    ],
  },
  {
    label: "数据属性",
    name: "dataForm",
    rules: {
      statIndctStatus: [
        { required: true, message: "请选择数据类型", trigger: "blur" },
      ],
      statIndctDataStyle: [
        { required: true, message: "请选择数据表示格式", trigger: "blur" },
      ],
      statIndctDataAcquisitionChannel: [
        { required: true, message: "请选择数据获取渠道", trigger: "blur" },
      ],
      statIndctDataRegionLevel: [
        { required: true, message: "请选择分地区数据级别", trigger: "blur" },
      ],
      statIndctDataPurpose: [
        { required: true, message: "请选择数据使用", trigger: "blur" },
      ],
    },
    fuData: {},
    data: [
      {
        label: "数据类型",
        width: "120px",
        prop: "statIndctDataType",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "数据表示格式",
        width: "120px",
        prop: "statIndctDataStyle",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "数据精度",
        width: "120px",
        prop: "statIndctDataPrecison",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "数据长度",
        width: "120px",
        prop: "statIndctDataLength",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "数据取值范围最大值",
        width: "120px",
        prop: "statIndctDataRangeMax",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "数据取值范围最小值",
        width: "120px",
        prop: "statIndctDataRangeMin",
        type: "input",
        disabled: false,
        placeholder: "",
      },
      {
        label: "数据获取渠道",
        width: "120px",
        prop: "statIndctDataAcquisitionChannel",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "分地区数据级别",
        width: "120px",
        prop: "statIndctDataRegionLevel",
        type: "select",
        disabled: false,
        placeholder: "",
      },
      {
        label: "数据使用",
        width: "120px",
        prop: "statIndctDataPurpose",
        type: "select",
        disabled: false,
        placeholder: "",
      },
    ],
  },
];
